---
title: An R Markdown document converted from "explDownSample.ipynb"
output: html_document
---

##### Setup

```{r}
suppressPackageStartupMessages(library(dplyr)) # data manipulation
suppressPackageStartupMessages(library(ggplot2)) # visualization
suppressPackageStartupMessages(library(ggthemes)) # visualization
suppressPackageStartupMessages(library(waffle))
suppressPackageStartupMessages(library(gridExtra))
library(corrplot)
library(caret)
suppressPackageStartupMessages(library(tidymodels))
```

```{r}
df <- read.csv('heart_2020_cleaned.csv', stringsAsFactors = T)
dfInit <- df
```

```{r}
sum(is.na(df))
```

```{r}
str(df)
```

##### Cleaning

```{r}
count(df,Diabetic)
```

```{r}
df <- df %>% 
    mutate(
        Diabetic=recode(Diabetic,
        `No, borderline diabetes`="Yes",
        `Yes (during pregnancy)`="No",))
```

```{r}
boolCols = c(match("HeartDisease",names(df)),match("Smoking",names(df)),match("AlcoholDrinking",names(df)),match("Stroke",names(df)),match("DiffWalking",names(df)),match("PhysicalActivity",names(df)),match("Asthma",names(df)),match("KidneyDisease",names(df)),match("SkinCancer",names(df)),match("Diabetic",names(df)))
df <- df %>% 
  mutate_at(boolCols,~ifelse(. %in% c('No'), FALSE, TRUE))
```

```{r}
count(df,SleepTime)
```

```{r}
count(df,AgeCategory)
```

```{r}
df <- df %>% 
    mutate(
        AgeCategory=recode(AgeCategory,
        `18-24`=1,
        `25-29`=2,
        `30-34`=3,
        `35-39`=4,
        `40-44`=5,
        `45-49`=6,
        `50-54`=7,
        `55-59`=8,
        `60-64`=9,
        `65-69`=10,
        `70-74`=11,
        `75-79`=12,
        `80 or older`=13,
        ))
```

```{r}
count(df,GenHealth)
```

```{r}
df <- df %>% 
    mutate(
        GenHealth=recode(GenHealth,
        `Poor`=1,
        `Fair`=2,
        `Good`=3,
        `Very good`=4,
        `Excellent`=5,))
```

```{r}
count(df,Race)
```

```{r}
dfAugment <- df
```

##### Exploration

```{r}
head(df)
```

```{r}
df %>% 
group_by(HeartDisease) %>% 
summarise(len=n()) %>%
  mutate(percent=round((len/nrow(df))*100,1))
 
options(repr.plot.width=15, repr.plot.height=5)
temp <- df %>% 
group_by(HeartDisease) %>% 
summarise(len=n()) %>%
mutate(len=round(len/1000,0))

temp[1,2] = temp[1,2]+1

temp1 <-setNames(temp$len, c('Healthy (91.4%)','Diseased (8.6%)'))
temp1 %>% waffle(rows=10,colors = c("#f8766d","#00bfc4")) + ggtitle("Percentage of Diseased") + 
theme(legend.key.size = unit(2, 'cm'), #change legend key size
        legend.key.height = unit(1.3, 'cm'), #change legend key height
        legend.key.width = unit(1.3, 'cm'), #change legend key width
        legend.text = element_text(size=20),
        plot.title = element_text(size=30))
```

```{r}
p1 <- ggplot(df, aes(x = AgeCategory, fill = HeartDisease)) +
  geom_bar(stat='count', position='dodge') +
  scale_x_continuous(breaks=c(1:13)) +
  labs(x = 'Age Group') +
  theme_few()

p2 <- ggplot(df, aes(x = GenHealth, fill = HeartDisease)) +
  geom_bar(stat='count', position='dodge') +
  scale_x_continuous(breaks=c(1:5)) +
  labs(x = 'General Health') +
  theme_few()

p3 <- df %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>%
  ggplot(aes(x=AgeCategory, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  geom_hline(yintercept=8.6, linetype="dashed", color = "red",size=1) +
  labs(x = 'Age Group',y="Percentage of Diseased") +
  theme_few()

p4 <- df %>%
  group_by(GenHealth)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>%
  ggplot(aes(x=GenHealth, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:5)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  geom_hline(yintercept=8.6, linetype="dashed", color = "red",size=1) +
  labs(x = 'General Health',y="Percentage of Diseased") +
  theme_few()

options(repr.plot.width=17, repr.plot.height=10)
grid.arrange(p1,p3,p2,p4,nrow = 2,widths = c(2,1.5))
```

```{r}
dfAugment %>%
  group_by(BMICat)%>%
  summarise(sum=sum(DiffWalking),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1))
```

```{r}
dfAugment %>%
  group_by(MentalHealthCat)%>%
  summarise(sum=sum(Smoking),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1))
```

```{r}
dfAugment %>%
  group_by(MentalHealthCat)%>%
  summarise(sum=sum(Stroke),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1))
```

```{r}
len = nrow(dfAugment)
dfAugment %>% 
  group_by(MentalHealthCat) %>%
  count(BMICat) %>% 
        pivot_wider(names_from = BMICat,
                    names_glue = "BMICat= {BMICat}", 
                    values_from = n)
```

```{r}
dfAugment %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(DiffWalking),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>% 
  ggplot(aes(x=AgeCategory, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'Age Group',y="Percentage of Difficulty Walking") +
  geom_hline(yintercept=13.88, linetype="dashed", color = "red",size=1) +
  theme_few()
```

```{r}
dfAugment %>%
summarise(sum=sum(Diabetic),len=n()) %>%
mutate(percentOfDiseased=round((sum/len)*100,1))
```

```{r}
options(repr.plot.width=10, repr.plot.height=7)

dfAugment %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(Diabetic),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>% 
  ggplot(aes(x=AgeCategory, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'Age Group',y="Percentage of Diabetes") +
  geom_hline(yintercept=14.9, linetype="dashed", color = "red",size=1) +
  theme_few()
```

```{r}
temp <- df %>%
  count(DiffWalking) %>%       
  group_by(DiffWalking) 
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
temp <- df %>%
  filter(DiffWalking==TRUE) %>%
  count(DiffWalking,Stroke) %>%       
  group_by(DiffWalking)
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
temp <- df %>%
  filter(DiffWalking==TRUE) %>%
  count(DiffWalking,KidneyDisease) %>%       
  group_by(DiffWalking)
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
temp <- df %>%
  filter(DiffWalking==TRUE) %>%
  count(DiffWalking,Diabetic) %>%       
  group_by(DiffWalking)
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
temp <- df %>%
  count(AlcoholDrinking) %>%       
  group_by(AlcoholDrinking) 
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
options(repr.plot.width=8, repr.plot.height=5)

df %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>%
  ggplot(aes(x=AgeCategory, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  geom_hline(yintercept=8.6, linetype="dashed", color = "red",size=1) +
  labs(x = 'Age Group',y="Percentage of Diseased") +
  theme_few()
```

```{r}
options(repr.plot.width=8, repr.plot.height=5)

dfAugment %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(AlcoholDrinking),len=n()) %>%
  mutate(percentOfDrinkers=round((sum/len)*100,1)) %>% 
  ggplot(aes(x=AgeCategory, y=percentOfDrinkers)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'Age Group',y="Percentage of Heavy Alcohol Drinkers") +
  geom_hline(yintercept=6.8, linetype="dashed", color = "red",size=1) +
  theme_few()
```

```{r}
temp <- df %>%
  count(Stroke) %>%       
  group_by(Stroke) 
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
options(repr.plot.width=8, repr.plot.height=5)

dfAugment %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(Stroke),len=n()) %>%
  mutate(percentOfDrinkers=round((sum/len)*100,1)) %>% 
  ggplot(aes(x=AgeCategory, y=percentOfDrinkers)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'Age Group',y="Percentage of Stroke") +
  geom_hline(yintercept=3.8, linetype="dashed", color = "red",size=1) +
  theme_few()
```

```{r}
dfAugment %>%
summarise(sum=sum(Stroke),len=n()) %>%
mutate(percentOfDiseased=round((sum/len)*100,1))
```

```{r}
options(repr.plot.width=8, repr.plot.height=5)
dfAugment %>%
  group_by(AgeCategory)%>%
  summarise(sum=sum(KidneyDisease),len=n()) %>%
  mutate(percentOfDrinkers=round((sum/len)*100,1)) %>% 
  ggplot(aes(x=AgeCategory, y=percentOfDrinkers)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'Age Group',y="Percentage of Kidney Disease") +
  geom_hline(yintercept=3.7, linetype="dashed", color = "red",size=1) +
  theme_few()
```

```{r}
p5 <- df %>%
  group_by(MentalHealth)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>%
  ggplot(aes(x=MentalHealth, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous() +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'MentalHealth',y="Percentage of Diseased") +
  theme_few()

p6 <- df %>%
  group_by(PhysicalHealth)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(percentOfDiseased=round((sum/len)*100,1)) %>%
  ggplot(aes(x=PhysicalHealth, y=percentOfDiseased)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous() +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  labs(x = 'PhysicalHealth',y="Percentage of Diseased") +
  theme_few()

options(repr.plot.width=11, repr.plot.height=10)
grid.arrange(p5,p6,nrow = 2)
```

```{r}
BMImeans <- df %>%
select(BMI,HeartDisease) %>% 
  group_by(HeartDisease) %>% 
  summarise(median=median(BMI))

bmi <- ggplot(df, aes(x=BMI, color=HeartDisease)) +
  geom_density(alpha=0.1,size=1)+
  geom_vline(data=BMImeans,aes(xintercept=median, color=HeartDisease),linetype="dashed",size=0.7) +
  theme_few()

SleepTimeMeans <- df %>%
select(SleepTime,HeartDisease) %>% 
  group_by(HeartDisease) %>% 
  summarise(median=median(SleepTime))

sleep <- ggplot(df, aes(x=SleepTime, color=HeartDisease)) +
  geom_density(alpha=0.1,size=1)+
  geom_vline(data=SleepTimeMeans,aes(xintercept=median, color=HeartDisease),linetype="dashed",size=0.7) +
  theme_few()

options(repr.plot.width=15, repr.plot.height=7)
grid.arrange(bmi,sleep,nrow = 2)
# Maybe we discretize meental and physical in 3 categories, poor-fair-good
```

```{r}
smoke <- df %>%
  count(Smoking, HeartDisease) %>%       
  group_by(Smoking) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(Smoking, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Smoking") +
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  ylab("") + 

  theme_bw()

alcohol <- df %>%
  count(AlcoholDrinking, HeartDisease) %>%       
  group_by(AlcoholDrinking) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(AlcoholDrinking, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Alcohol") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

stroke <- df %>%
  count(Stroke,HeartDisease) %>%       
  group_by(Stroke) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(Stroke, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Stroke") +
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  ylab("") + 
  theme_bw()

walking <- df %>%
  count(DiffWalking,HeartDisease) %>%       
  group_by(DiffWalking) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(DiffWalking, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Difficulty Walking") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

diabetes <- df %>%
  count(Diabetic,HeartDisease) %>%       
  group_by(Diabetic) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(Diabetic, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Diabetes") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

activity <- df %>%
  count(PhysicalActivity,HeartDisease) %>%       
  group_by(PhysicalActivity) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(PhysicalActivity, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Physical Activity") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

asthma <- df %>%
  count(Asthma,HeartDisease) %>%       
  group_by(Asthma) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(Asthma, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Asthma") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

kidney <- df %>%
  count(KidneyDisease,HeartDisease) %>%       
  group_by(KidneyDisease) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(KidneyDisease, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Kidney Disease") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

skin <- df %>%
  count(SkinCancer,HeartDisease) %>%       
  group_by(SkinCancer) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(SkinCancer, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Skin Cancer") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

options(repr.plot.width=15, repr.plot.height=15)
grid.arrange(smoke,alcohol,stroke,walking,diabetes,activity,asthma,kidney,skin,nrow = 3)
```

```{r}
sex <- df %>%
  count(Sex,HeartDisease) %>%       
  group_by(Sex) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(Sex, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Sex") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

race <- df %>%
  count(Race,HeartDisease) %>%       
  group_by(Race) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(Race, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("Etnicity") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

options(repr.plot.width=15, repr.plot.height=5)
grid.arrange(sex,race,nrow =1)
```

```{r}
temp <- df %>%
  count(Sex,AgeCategory) %>%       
  group_by(Sex)
temp$pct= 100*(temp$n/sum(temp$n))
temp

temp %>% 
  ggplot(aes(x=AgeCategory,y=n,color=Sex)) +
  geom_line() +
  geom_point() +
  ylab("Number of respondents") + 
  theme_few()
```

```{r}
temp <- df %>%
  count(Sex,GenHealth) %>%       
  group_by(Sex)
temp$pct= 100*(temp$n/sum(temp$n))
temp %>% 
  ggplot(aes(x=GenHealth,y=n,color=Sex)) +
  geom_line() +
  geom_point() +
  ylab("Number of respondents") + 
  theme_few()
```

```{r}
options(repr.plot.width=9, repr.plot.height=6)
active <- df %>%
  filter(PhysicalActivity==TRUE) %>% 
  group_by(AgeCategory)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(diseasedActivePercent=round((sum/len)*100,1))

notActive <- df %>%
  filter(PhysicalActivity==FALSE) %>% 
  group_by(AgeCategory)%>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(diseasedNotActivePercent=round((sum/len)*100,1))

joined_tibble <- left_join(active, notActive, 
              by = c("AgeCategory" = "AgeCategory"))


joined_tibble %>% 
  ggplot(aes(x=AgeCategory)) +
  geom_line(aes(y=diseasedActivePercent,color="Active"), size=1) +
  geom_line(aes(y=diseasedNotActivePercent,color="NotActive"), size=1) +
  geom_point(aes(y=diseasedNotActivePercent,color="NotActive"), size=3,shape=17)+
  geom_point(aes(y=diseasedActivePercent,color="Active"), size=3,shape=15)+
  scale_x_continuous(breaks=c(1:13)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  labs(x = 'Age Group',y="Percentage of Diseased") +
  ggtitle("Does Physical Activity help older people too?") +
  scale_colour_manual("", 
                      values = c("Active"="#f8766d", "NotActive"="#00bfc4")) +
  theme_few()

joined_tibble$diff <- joined_tibble$diseasedNotActivePercent -  joined_tibble$diseasedActivePercent

mean(joined_tibble$diff[6:13])
mean(joined_tibble$diff)
```

```{r}
dfAugment <- dfAugment %>%
    mutate(nCommorbs = rowSums(.[,c("Stroke","Asthma","KidneyDisease","SkinCancer","Diabetic")]))

options(repr.plot.width=8, repr.plot.height=5)

dfAugment %>%
  group_by(nCommorbs) %>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(diseasedActivePercent=round((sum/len)*100,1)) %>%
  ggplot(aes(x=nCommorbs, y=diseasedActivePercent)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(0:5)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  geom_hline(yintercept=8.6, linetype="dashed", color = "red",size=1) +
  labs(x = 'Number of comorbities',y="Percentage of Diseased") +
  theme_few()
```

```{r}
# https://www.cdc.gov/obesity/basics/adult-defining.html
# Over 30 is obesity [4 and 5]
dfAugment <- dfAugment %>% 
    mutate(
        BMICat=
        case_when(
         BMI<18.5 ~ 1,
         BMI>= 18.5 & BMI<25 ~ 2,
         BMI>= 25 & BMI<30 ~ 3,
         BMI>= 30 ~ 4))


# https://www.cdc.gov/sleep/about_sleep/how_much_sleep.html
# 7-10 is okay 
dfAugment <- dfAugment %>% 
    mutate(
        SleepTimeCat=
        case_when(
         SleepTime<4 ~ 1,
         SleepTime>= 4 & SleepTime<7 ~ 2,
         SleepTime>= 7 & SleepTime<13 ~ 3,
         SleepTime>= 13  ~ 4))

dfAugment <- dfAugment %>% 
    mutate(
        PhysicalHealthCat=
        case_when(
         PhysicalHealth<10 ~ 1,
         PhysicalHealth>= 10 & PhysicalHealth<20 ~ 2,
         PhysicalHealth>= 20 ~ 3,))

dfAugment <- dfAugment %>% 
    mutate(
        MentalHealthCat=
        case_when(
         MentalHealth<10 ~ 1,
         MentalHealth>= 10 & MentalHealth<20 ~ 2,
         MentalHealth>= 20 ~ 3,))
```

```{r}
bmi <- dfAugment %>%
  count(BMICat, HeartDisease) %>%       
  group_by(BMICat) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(BMICat, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("BMI") +
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  ylab("") + 

  theme_bw()

sleepTime <- dfAugment %>%
  count(SleepTimeCat, HeartDisease) %>%       
  group_by(SleepTimeCat) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(SleepTimeCat, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("SleepTime") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()

phys <- dfAugment %>%
  count(PhysicalHealthCat,HeartDisease) %>%       
  group_by(PhysicalHealthCat) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(PhysicalHealthCat, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("PhysicalHealth") +
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  ylab("") + 
  theme_bw()

mental <- dfAugment %>%
  count(MentalHealthCat,HeartDisease) %>%       
  group_by(MentalHealthCat) %>%
  mutate(pct= prop.table(n) * 100) %>%
  ggplot() + aes(MentalHealthCat, pct, fill=HeartDisease) +
  geom_bar(stat="identity") +
  geom_text(aes(label=paste0(sprintf("%1.1f", pct),"%")),colour="white",
            position=position_stack(vjust=0.5)) +
  ggtitle("MentalHealth") +
  ylab("") + 
  geom_hline(yintercept=8.6, linetype="dashed", color = "white") +
  theme_bw()


options(repr.plot.width=15, repr.plot.height=10)
grid.arrange(bmi,sleepTime,phys,mental,nrow = 2)
```

```{r}
temp <- dfAugment %>%
  count(Stroke) %>%       
  group_by(Stroke) 
temp$pct= 100*(temp$n/sum(temp$n))
temp
```

```{r}
# Computing number of Bad Habits 
dfAugment <- dfAugment %>%
  mutate(habit1 = if_else(BMICat == 4, 1, 0),
         habit2 = if_else(SleepTimeCat == 1 | SleepTimeCat == 4, 1, 0),
         habit3 = if_else(MentalHealthCat ==2|MentalHealthCat==3,1,0),
         habit4 = if_else(Smoking==TRUE,1,0),
         habit5 = if_else(PhysicalActivity==FALSE,1,0),
         nBadHabits = habit1 + habit2 + habit3 +habit4 +habit5) %>% 
  select(-c(habit1, habit2,habit3,habit4,habit5))

dfAugment %>%
  group_by(nBadHabits) %>%
  summarise(sum=sum(HeartDisease),len=n()) %>%
  mutate(diseasedActivePercent=round((sum/len)*100,1)) %>%
  ggplot(aes(x=nBadHabits, y=diseasedActivePercent)) +
  geom_line(linetype = "twodash",color="#00bfc4",size=1) +
  scale_x_continuous(breaks=c(0:5)) +
  scale_y_continuous(labels = function(x) paste0(x, "%")) +
  geom_point(color="#137085",size=3) +
  geom_hline(yintercept=8.6, linetype="dashed", color = "red",size=1) +
  labs(x = 'Number of bad habits',y="Percentage of Diseased") +
  ylim(0,30) +
  theme_few()
```

```{r}
# Alcohol is good for you?
dfAugment[,c("AlcoholDrinking","GenHealth","nBadHabits","nCommorbs","AgeCategory","BMI","SleepTimeCat","PhysicalHealth","MentalHealth")] %>%
group_by(AlcoholDrinking) %>%
summarise(across(
    .cols = is.numeric, 
    .fns = list(Mean = mean, SD = sd), na.rm = TRUE, 
    .names = "{col}_{fn}"
    ))
```

```{r}
# Why women get less heart diseases are them healthier? (no)
dfAugment[,c("Sex","GenHealth","nBadHabits","nCommorbs","AgeCategory","BMI","SleepTimeCat","PhysicalHealth","MentalHealth")] %>%
group_by(Sex) %>%
summarise(across(
    .cols = is.numeric, 
    .fns = list(Mean = mean, SD = sd), na.rm = TRUE, 
    .names = "{col}_{fn}"
    ))
```

```{r}
# Extremely interesting correlations honestly, talk about in the paper
options(repr.plot.width=15, repr.plot.height=10)

nums <- unlist(lapply(dfAugment, is.numeric), use.names = FALSE)

M<-cor(dfAugment[ , nums])

# mat : is a matrix of data
# ... : further arguments to pass to the native R cor.test function
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(dfAugment[ , nums])

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(M, method="color", col=col(200),  
         type="upper", order="hclust", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```

```{r}
write.csv(dfAugment,"agumented.csv", row.names = FALSE)
```

##### Logistic Regression and Optimal Threshold study (I'm not using the Numerical variables at their best because theyre not linear!!!! Must use categorical ones I created)

##### Tree

##### Neural Networks with Class Weights

##### Other stuff

```{r}
write.csv(df,"cleaned.csv", row.names = FALSE)
```

```{r}
mySetOfMetrics <- metric_set(accuracy,bal_accuracy,f_meas)
```

```{r}
set.seed(420)
split_full <- initial_split(df, prop = 0.80,strata =HeartDisease)
train_full <- training(split_full)
test_full  <-  testing(split_full)

downSampledDf <- downSample(x = train_full[,-c(1)],y = train_full$HeartDisease)

split_downsample <- initial_split(downSampledDf, prop = 0.80,strata =Class)
train_downsample <- training(split_downsample)
test_downsample  <-  testing(split_downsample)
```

```{r}
lr_spec <- logistic_reg() %>%
  set_engine("glm") %>%
  set_mode("classification")

lr_fit <- lr_spec %>%
  fit(
    Class ~ .,
    data = downSampledDf
    )

lr_fit %>%
  pluck("fit") %>%
  summary()

#augment(lr_fit, new_data = test) %>%
#  conf_mat(truth = Class, estimate = .pred_class) 

#augment(lr_fit, new_data = test) %>%
#  mySetOfMetrics(truth = Class, estimate = .pred_class,event_level="second") 
```

```{r}
cv_folds <- vfold_cv(downSampledDf, v = 10)

mySpec <- logistic_reg() %>%
  set_engine("glm") %>%
  set_mode("classification")

ao <- fit_resamples(mySpec,Class ~ .,resamples = cv_folds, metrics=mySetOfMetrics)
```

```{r}
logRegFolds <- collect_metrics(ao)
logRegFolds
```

```{r}
augment(lr_fit, new_data = test_full) %>%
  conf_mat(truth = HeartDisease, estimate = .pred_class) 

augment(lr_fit, new_data = test_full) %>%
  mySetOfMetrics(truth = HeartDisease, estimate = .pred_class,event_level="second") 
```

